-- MySQL Script generated by MySQL Workbench
-- Tue Jun 16 12:49:22 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`meta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`meta` (
  `idmeta` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(90) NOT NULL,
  `descricao` VARCHAR(256) NOT NULL,
  `valoratual` DOUBLE NOT NULL,
  `valormeta` DOUBLE NOT NULL,
  `imagem` VARCHAR(256) NOT NULL,
  `datalimite` DATETIME NULL,
  `publica` TINYINT NOT NULL,
  PRIMARY KEY (`idmeta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`banco` (
  `idbanco` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `codigo` INT NOT NULL,
  PRIMARY KEY (`idbanco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(256) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `email` VARCHAR(90) NOT NULL,
  `senha` VARCHAR(90) NOT NULL,
  `telefone` VARCHAR(14) NOT NULL,
  `imagem` VARCHAR(256) NULL,
  `banco_idbanco` INT NOT NULL,
  `agencia` INT NULL,
  `conta` INT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_banco_idx` (`banco_idbanco` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_banco`
    FOREIGN KEY (`banco_idbanco`)
    REFERENCES `mydb`.`banco` (`idbanco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`doacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`doacao` (
  `iddoacao` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `valor` DOUBLE NOT NULL,
  `mensagem` VARCHAR(256) NULL,
  `anonima` TINYINT NOT NULL,
  `notificado` TINYINT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `meta_idMeta` INT NOT NULL,
  PRIMARY KEY (`iddoacao`),
  INDEX `fk_doacao_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_doacao_meta1_idx` (`meta_idMeta` ASC) VISIBLE,
  CONSTRAINT `fk_doacao_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doacao_meta1`
    FOREIGN KEY (`meta_idMeta`)
    REFERENCES `mydb`.`meta` (`idmeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`saque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`saque` (
  `idsaque` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `valor` DOUBLE NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `meta_idmeta` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idsaque`),
  INDEX `fk_saque_meta1_idx` (`meta_idmeta` ASC) VISIBLE,
  INDEX `fk_saque_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_saque_meta1`
    FOREIGN KEY (`meta_idmeta`)
    REFERENCES `mydb`.`meta` (`idmeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_saque_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`notificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`notificacao` (
  `idnotificacao` INT NOT NULL AUTO_INCREMENT,
  `mensagem` VARCHAR(256) NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `saque_idsaque` INT NULL,
  `meta_idmeta` INT NOT NULL,
  PRIMARY KEY (`idnotificacao`),
  INDEX `fk_notificacao_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_notificacao_saque1_idx` (`saque_idsaque` ASC) VISIBLE,
  INDEX `fk_notificacao_meta1_idx` (`meta_idmeta` ASC) VISIBLE,
  CONSTRAINT `fk_notificacao_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notificacao_saque1`
    FOREIGN KEY (`saque_idsaque`)
    REFERENCES `mydb`.`saque` (`idsaque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notificacao_meta1`
    FOREIGN KEY (`meta_idmeta`)
    REFERENCES `mydb`.`meta` (`idmeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
