-- MySQL Script generated by MySQL Workbench
-- Sat Jun 27 12:53:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Bank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bank` (
  `idBank` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(90) NOT NULL,
  `code` INT NOT NULL,
  PRIMARY KEY (`idBank`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(90) NOT NULL,
  `lastname` VARCHAR(256) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `age` INT NULL,
  `email` VARCHAR(90) NOT NULL,
  `phone` VARCHAR(14) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `bankAgency` INT NOT NULL,
  `bankAccount` INT NOT NULL,
  `imgPath` VARCHAR(256) NULL,
  `Bank_idBank` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  INDEX `fk_User_Bank1_idx` (`Bank_idBank` ASC) VISIBLE,
  CONSTRAINT `fk_User_Bank1`
    FOREIGN KEY (`Bank_idBank`)
    REFERENCES `mydb`.`Bank` (`idBank`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Goal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Goal` (
  `idGoal` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(256) NOT NULL,
  `value` DOUBLE NOT NULL,
  `goalValue` DOUBLE NULL,
  `createDate` DATETIME NOT NULL,
  `goalDate` DATETIME NULL,
  `idUser` INT NOT NULL,
  `isPublic` TINYINT NOT NULL,
  `imgPath` VARCHAR(256) NULL,
  PRIMARY KEY (`idGoal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Notification` (
  `idNotification` INT NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(256) NOT NULL,
  `Goal_idGoal` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idNotification`),
  INDEX `fk_Notification_Goal1_idx` (`Goal_idGoal` ASC) VISIBLE,
  INDEX `fk_Notification_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Notification_Goal1`
    FOREIGN KEY (`Goal_idGoal`)
    REFERENCES `mydb`.`Goal` (`idGoal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notification_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Donation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Donation` (
  `idDonation` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `valor` DOUBLE NOT NULL,
  `message` VARCHAR(256) NULL,
  `isAnonymous` TINYINT NOT NULL,
  `isPublic` TINYINT NOT NULL,
  `User_idUser` INT NOT NULL,
  `Goal_idGoal` INT NOT NULL,
  PRIMARY KEY (`idDonation`),
  INDEX `fk_Donation_User1_idx` (`User_idUser` ASC) VISIBLE,
  INDEX `fk_Donation_Goal1_idx` (`Goal_idGoal` ASC) VISIBLE,
  CONSTRAINT `fk_Donation_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Donation_Goal1`
    FOREIGN KEY (`Goal_idGoal`)
    REFERENCES `mydb`.`Goal` (`idGoal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Booty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Booty` (
  `idBooty` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `value` DOUBLE NOT NULL,
  `status` VARCHAR(256) NOT NULL,
  `User_idUser` INT NOT NULL,
  `Goal_idGoal` INT NOT NULL,
  PRIMARY KEY (`idBooty`),
  INDEX `fk_Booty_User1_idx` (`User_idUser` ASC) VISIBLE,
  INDEX `fk_Booty_Goal1_idx` (`Goal_idGoal` ASC) VISIBLE,
  CONSTRAINT `fk_Booty_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Booty_Goal1`
    FOREIGN KEY (`Goal_idGoal`)
    REFERENCES `mydb`.`Goal` (`idGoal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
