-- MySQL Script generated by MySQL Workbench
-- Mon Jun  8 20:24:53 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Meta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Meta` (
  `idMeta` INT NOT NULL AUTO_INCREMENT,
  `dono` INT NOT NULL,
  `titulo` VARCHAR(256) NOT NULL,
  `descricao` VARCHAR(256) NOT NULL,
  `valor` REAL NOT NULL,
  `valorMeta` REAL NOT NULL,
  `dataLimite` DATETIME NULL,
  `ehPublico` TINYINT NOT NULL,
  `imagem` VARCHAR(256) NULL,
  PRIMARY KEY (`idMeta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Banco` (
  `idBanco` INT NOT NULL,
  `nome` VARCHAR(256) NOT NULL,
  `codigo` INT NOT NULL,
  `agencia` VARCHAR(45) NOT NULL,
  `conta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBanco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(256) NOT NULL,
  `sobrenome` VARCHAR(256) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `email` VARCHAR(256) NOT NULL,
  `senha` VARCHAR(256) NOT NULL,
  `telefone` VARCHAR(256) NOT NULL,
  `Banco_idBanco` INT NOT NULL,
  `imagem` VARCHAR(256) NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Banco1_idx` (`Banco_idBanco` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Banco1`
    FOREIGN KEY (`Banco_idBanco`)
    REFERENCES `mydb`.`Banco` (`idBanco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Doacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Doacao` (
  `idTransacao` INT NOT NULL,
  `data` DATETIME NOT NULL,
  `valor` REAL NOT NULL,
  `mensagem` VARCHAR(256) NULL,
  `Meta_idMeta` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `ehAnonimo` TINYINT NOT NULL,
  `ehNotificado` TINYINT NOT NULL,
  PRIMARY KEY (`idTransacao`),
  INDEX `fk_Transacao_Meta1_idx` (`Meta_idMeta` ASC) VISIBLE,
  INDEX `fk_Transacao_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Transacao_Meta1`
    FOREIGN KEY (`Meta_idMeta`)
    REFERENCES `mydb`.`Meta` (`idMeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transacao_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Notificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Notificacao` (
  `idNotificacao` INT NOT NULL,
  `mensagem` VARCHAR(256) NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Meta_idMeta` INT NOT NULL,
  PRIMARY KEY (`idNotificacao`),
  INDEX `fk_Notificacao_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_Notificacao_Meta1_idx` (`Meta_idMeta` ASC) VISIBLE,
  CONSTRAINT `fk_Notificacao_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notificacao_Meta1`
    FOREIGN KEY (`Meta_idMeta`)
    REFERENCES `mydb`.`Meta` (`idMeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Saque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Saque` (
  `idSaque` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `valor` REAL NOT NULL,
  `status` VARCHAR(256) NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Meta_idMeta` INT NOT NULL,
  PRIMARY KEY (`idSaque`),
  INDEX `fk_Saque_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_Saque_Meta1_idx` (`Meta_idMeta` ASC) VISIBLE,
  CONSTRAINT `fk_Saque_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Saque_Meta1`
    FOREIGN KEY (`Meta_idMeta`)
    REFERENCES `mydb`.`Meta` (`idMeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
